let a = 20;
try{
	conole.log(a);
}

catch(error){
	console.log(error.message);
}